#+TITLE:     Notes on SICP
#+AUTHOR:    Martín Rodriguez
#+EMAIL:     mtrpdx@gmail.com

* Chapter 1
** [X] Programming in Lisp
*** computational process
*** recursion equations
"Recursive Functions of Symbolic Expressions and Their Computation by Machine" (McCarthy 1960)
*** data objects: atoms and lists
*** procedures can be manipulated as data
** [X] 1-1 The Elements of Programming
*** Ways to form complex ideas from simple ideas
**** primitive expressions:
represent the simplest entities the language is concerned with
**** means of combination:
how compound elements are built from simpler ones
**** means of abstraction:
how compound elements can be named and manipulated as units
*** Use `define' to name variables
*** global environment:
"memory" that keeps track of name-object pairs for symbols/variables
*** recursion is an inherent part of evaluation
*** tree accumulation:
"percolate values upward"
*** syntactic sugar:
special syntactic forms that are convenient alternative surface structures for things that can be written in more uniform ways
*** procedure definition:
(define (<NAME> <FORMAL PARAMETERS>) <BODY>)
*** "substitution model" for procedure application
*** Stoy 1977 for substitution reference
*** substitution is actually accomplished by using a local environment for the formal parameters
*** evaluation (applicative-order):
interpreter first evaluates the operator and operands and then applies the resulting procedure to the resulting arguments
*** alternative model for evaluation (normal-order):
do not evaluate operands until their values are needed; instead first substitute operand expressions for parameters until an expression involving only primitive operators is obtained, then perform evaluation
*** Lisp uses applicative-order evaluation
*** Conditional expressions (each <E> may be a sequence of expressions)
(cond (<P1> <E1>)
      (<P2> <E2>)
      ...
      (<PN> <EN>)

where each (<P> <E>) is a "clause," each <P> is a predicate, and each <E> is a "consequent expression"
*** predicate:
procedure that returns true or false or an expression that evaluates to true or false
*** if (used when there are precisely two cases, <P> and <E> must be single expressions):
(if <PREDICATE> <CONSEQUENT> <ALTERNATIVE>)
*** In math: concerned with declarative knowledge (what is)
*** In computer science: concerned with imperative knowledge (how to)
*** Newton's method of successive approximations to compute square root
*** Floating-point arithmetic
Ulps: units in the last place, a way to measure floating point error from values calculated to infinite precision
relative error: Difference between floating point number and the real number it is approximating, divided by the real number
Wobble: Relative error corresponding to 0.5 ulp varies by a factor of β
Machine epsilon: relative error is bounded by e
In general, when the base is β, a fixed relative error expressed in ulps can wobble by a factor of up to β. A fixed error of 0.5 ulps results in a relative error that can wobble by β.
Contaminated digits are about log Β n
Guard digits: digit used to protect against the rightmost digit getting shifted off in calculations
Without a guard digit, the relative error committed when subtracting two nearby quantities can be very large.
Catastrophic cancellation: occurs when operands are subject to rouding errors
Benign cancellation: occurs when subtracting exactly known quantities (x and y have no rounding error)
*** Procedural abstraction:
abstraction of a procedure with regards to another calling procedure so that it appears to be a "black box"
*** Parameter names:
local to their respective procedures. The procedure definition "binds" its formal parameters
*** Bound vs. free variables:
bound variable: meaning of procedure is independent from the names of bound variables
free variable: meaning of procedure is dependent on names of free variables
*** Lexical scoping:
Allow bound variables to be free variables in the internal definitions of procedures, so that the variables get their value from the argument with which the enclosing procedure is called.

** [ ] 1-2 Procedures and the Processes they Generate
*** Linear iterative processes vs linear recursive processes
Recursive processes look like expansion (deferred operations) followed by a contraction (performed operations) when viewed with the substitution model
Iterative processes do not expand/contract and its state can be summarized by a fixed number of "state variables" and a rule to describe how the state variables should be updated. An optional end test is often used to decide when to terminate.
*** Tail recursion
The scheme we are using is "tail-recursive," meaning it executes iterative processes in constant space, even if the iterative process is described by a recursive procedure.
*** Ackermann's function
*** Tree recursion
** [ ] 1-3 Formulating Abstractions with Higher-Order Procedures
* Chapter 2
** [ ] Building Abstractions with Data
** [ ] Introduction to Data Abstraction
** [ ] Hierarchical Data and the Closure Property
** [ ] Symbolic Data
** [ ] Multiple Representations for Abstract Data
** [ ] Systems with Generic Operations
* Chapter 3
** [ ] Modularity, Objects, and State
** [ ] Assignment and Local State
** [ ] The Environment Model of Evaluation
** [ ] Modeling with Mutable Data
** [ ] Concurrency: Time Is of the Essence
** [ ] Streams
* Chapter 4
** [ ] Metalinguistic Abstraction
** [ ] The Metacircular Evaluator
** [ ] Variations on a Scheme -- Lazy Evaluation
** [ ] Variations on a Scheme -- Nondeterministic Computing
** [ ] Logic Programming
** [ ] Implementing the Query System
* Chapter 5
** [ ] Computing with Register Machines
** [ ] Designing Register Machines
** [ ] A Register-Machine Simulator
** [ ] Storage Allocation and Garbage Collection
** [ ] Registers and Operations
** [ ] An Overview of the Compiler
